parser: babel-eslint
extends: standard

plugins:
  - react
  - import

parserOptions:
  ecmaFeatures:
    jsx: true

env:
  browser: true
  mocha: true
  jest: true

globals:
  __DEV__: false
  __PROD__: false
  __DEBUG__: false
  __DEBUG_NW__: false
  browser: false

settings:
  import/resolver:
    node:
      paths:
        - ./src
        - ./

rules:
  import/no-unresolved: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
