export const REPO_CONTENTS_REQUEST = 'content-list/REPO_CONTENTS_REQUEST'
export const REPO_CONTENTS_SUCCESS = 'content-list/REPO_CONTENTS_SUCCESS'
export const REPO_CONTENTS_FAILURE = 'content-list/REPO_CONTENTS_FAILURE'
